MAIN_PAGE_URL = 'https://stellarburgers.nomoreparties.site/'
LOGIN_PAGE_URL = f'{MAIN_PAGE_URL}login'
RESET_PASSWORD_URL = f'{MAIN_PAGE_URL}forgot-password'
MY_ACCOUNT_URL = f'{MAIN_PAGE_URL}account/profile'
ORDER_FEED_URL = f'{MAIN_PAGE_URL}feed'

TEST_EMAIL = 'qwert1234@mail.com'
TEST_PASSWORD = '87654321QWERTY'

INGREDIENT_COUNT = 14
BUN_COUNT = 2

ORDER_ID_PLACEHOLDER = '9999'